import { writeFileSync } from "node:fs";
import { join } from "node:path";
import hre from "hardhat";
import { deployments, CHAIN_META, type ContractAddresses } from "@agentrail/shared";

const OUT = join(__dirname, "..", "..", "shared", "src", "deployments.ts");

const HEADER = `// AUTO-GENERATED by packages/contracts/scripts/deploy.ts — do not edit by hand.
// Keyed by chain id. Deploying to one chain preserves the other chains' entries.
// Zero addresses mean "not deployed to that chain yet".
import type { ContractAddresses } from "./types";

export const deployments: Record<number, ContractAddresses> = {
`;

function renderEntry(chainId: number, addrs: ContractAddresses): string {
  const fields = (Object.keys(addrs) as (keyof ContractAddresses)[])
    .map((name) => `    ${name}: "${addrs[name]}",`)
    .join("\n");
  return `  "${chainId}": {\n${fields}\n  },`;
}

/// Deploys all AgentRail contracts to the target network and records their
/// addresses in packages/shared/src/deployments.ts under the connected chain
/// id, so every consumer imports one source of truth.
///   npm run deploy                 -> localhost (31337)
///   npm run deploy:base-sepolia    -> Base Sepolia (84532)
async function main() {
  const publicClient = await hre.viem.getPublicClient();
  const chainId = await publicClient.getChainId();
  const chainName = CHAIN_META[chainId]?.name ?? `chain ${chainId}`;

  console.log(`Deploying to ${chainName} (${chainId})...`);

  const usdc = await hre.viem.deployContract("MockUSDC");
  const jobContract = await hre.viem.deployContract("JobContract", [usdc.address]);
  const identityRegistry = await hre.viem.deployContract("IdentityRegistry");
  const reputationRegistry = await hre.viem.deployContract("ReputationRegistry");
  const evaluatorModule = await hre.viem.deployContract("EvaluatorModule", [jobContract.address]);

  const deployed: ContractAddresses = {
    MockUSDC: usdc.address,
    JobContract: jobContract.address,
    IdentityRegistry: identityRegistry.address,
    ReputationRegistry: reputationRegistry.address,
    EvaluatorModule: evaluatorModule.address,
  };

  // Merge rather than replace: deploying to testnet must not wipe the local
  // deployment (and vice versa) or the other network's consumers break.
  const merged: Record<number, ContractAddresses> = { ...deployments, [chainId]: deployed };

  const body = Object.keys(merged)
    .map(Number)
    .sort((a, b) => a - b)
    .map((id) => renderEntry(id, merged[id]!))
    .join("\n");

  writeFileSync(OUT, `${HEADER}${body}\n};\n`);

  console.log(`Deployed to ${chainName}:`, deployed);

  const explorer = CHAIN_META[chainId]?.explorer;
  if (explorer) {
    console.log(`Explorer: ${explorer}/address/${jobContract.address}`);
  }
  console.log("Wrote deployments ->", OUT);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
