import hre from "hardhat";
import fs from "fs";
import path from "path";
import {
  deployments,
  deploymentBlocks,
  CHAIN_META,
  type ContractAddresses,
} from "@agentrail/shared";

const SHARED_OUT = path.join(__dirname, "..", "..", "shared", "src", "deployments.ts");

const HEADER = `// AUTO-GENERATED by packages/contracts/scripts/deploy.ts — do not edit by hand.
// Keyed by chain id. Deploying to one chain preserves the other chains' entries.
// Zero addresses mean "not deployed to that chain yet".
import type { ContractAddresses } from "./types";

export const deployments: Record<number, ContractAddresses> = {
`;

// The block the contracts went live at. The indexer starts here instead of
// genesis — on a public chain that is the difference between seconds and
// scanning millions of empty blocks.
const BLOCKS_HEADER = `
export const deploymentBlocks: Record<number, number> = {
`;

function renderEntry(chainId: number, addrs: ContractAddresses): string {
  const fields = (Object.keys(addrs) as (keyof ContractAddresses)[])
    .map((name) => `    ${name}: "${addrs[name]}",`)
    .join("\n");
  return `  "${chainId}": {\n${fields}\n  },`;
}

/// Every consumer imports addresses from @agentrail/shared, so the deploy must
/// write there as well as to deployed-addresses.json. Merge rather than
/// replace: deploying to testnet must not wipe the local entry, or the other
/// network's agents and indexer break.
function writeSharedDeployments(
  chainId: number,
  deployed: ContractAddresses,
  block: number,
): void {
  const merged: Record<number, ContractAddresses> = { ...deployments, [chainId]: deployed };
  const mergedBlocks: Record<number, number> = { ...deploymentBlocks, [chainId]: block };

  const ids = Object.keys(merged).map(Number).sort((a, b) => a - b);
  const body = ids.map((id) => renderEntry(id, merged[id]!)).join("\n");
  const blocks = ids.map((id) => `  "${id}": ${mergedBlocks[id] ?? 0},`).join("\n");

  fs.writeFileSync(SHARED_OUT, `${HEADER}${body}\n};\n${BLOCKS_HEADER}${blocks}\n};\n`);
}

async function main() {
  console.log("Deploying AgentRail system contracts with Viem...");
  // Captured before the first deploy so the indexer never starts after an
  // event it needed. A few extra blocks scanned is harmless; missing one is not.
  const startBlock = Number(await (await hre.viem.getPublicClient()).getBlockNumber());
  const [deployer] = await hre.viem.getWalletClients();
  console.log("Deployer account:", deployer.account.address);

  // 1. Deploy MockUSDC
  const usdc = await hre.viem.deployContract("MockUSDC");
  console.log("MockUSDC deployed to:", usdc.address);

  // 2. Deploy JobContract
  const jobContract = await hre.viem.deployContract("JobContract", [usdc.address]);
  console.log("JobContract deployed to:", jobContract.address);

  // 3. Deploy IdentityRegistry
  const identityRegistry = await hre.viem.deployContract("IdentityRegistry");
  console.log("IdentityRegistry deployed to:", identityRegistry.address);

  // 4. Deploy ReputationRegistry
  const reputationRegistry = await hre.viem.deployContract("ReputationRegistry", [deployer.account.address]);
  console.log("ReputationRegistry deployed to:", reputationRegistry.address);

  // 5. Deploy EvaluatorModule
  const evaluatorModule = await hre.viem.deployContract("EvaluatorModule", [jobContract.address]);
  console.log("EvaluatorModule deployed to:", evaluatorModule.address);

  // 6. Wire permissions
  console.log("\nConfiguring cross-contract permissions...");
  await jobContract.write.setEvaluatorModule([evaluatorModule.address]);
  await jobContract.write.setReputationRegistry([reputationRegistry.address]);
  await reputationRegistry.write.setJobContract([jobContract.address]);

  console.log("All contracts wired successfully!");

  const addresses: ContractAddresses = {
    MockUSDC: usdc.address,
    JobContract: jobContract.address,
    IdentityRegistry: identityRegistry.address,
    ReputationRegistry: reputationRegistry.address,
    EvaluatorModule: evaluatorModule.address,
  };

  fs.writeFileSync(path.join(__dirname, "../deployed-addresses.json"), JSON.stringify(addresses, null, 2));

  const publicClient = await hre.viem.getPublicClient();
  const chainId = await publicClient.getChainId();
  writeSharedDeployments(chainId, addresses, startBlock);

  const chainName = CHAIN_META[chainId]?.name ?? `chain ${chainId}`;
  console.log(`\nDeployed to ${chainName} (${chainId})`);
  console.log("Saved addresses to deployed-addresses.json and shared/src/deployments.ts");

  const explorer = CHAIN_META[chainId]?.explorer;
  if (explorer) {
    console.log(`Explorer: ${explorer}/address/${jobContract.address}`);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
