// Regenerates packages/shared/src/abis/*.ts from the compiled Hardhat
// artifacts. Wired into `npm run compile`, so the ABIs every consumer imports
// cannot drift from the contracts again — hand-written fragments silently went
// stale once already when the contract interfaces changed.
//
// Plain .mjs on purpose: it only reads JSON, so it needs no ts-node or tsx.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ARTIFACTS = join(here, "..", "artifacts", "contracts");
const OUT_DIR = join(here, "..", "..", "shared", "src", "abis");

/// artifact path -> exported const name. MockUSDC is included because agents
/// must approve() before funding a job and the indexer reads Transfer events.
const CONTRACTS = [
  ["JobContract.sol/JobContract.json", "JobContractAbi"],
  ["EvaluatorModule.sol/EvaluatorModule.json", "EvaluatorModuleAbi"],
  ["IdentityRegistry.sol/IdentityRegistry.json", "IdentityRegistryAbi"],
  ["ReputationRegistry.sol/ReputationRegistry.json", "ReputationRegistryAbi"],
  ["mocks/MockUSDC.sol/MockUSDC.json", "MockUSDCAbi"],
];

mkdirSync(OUT_DIR, { recursive: true });

for (const [artifactPath, exportName] of CONTRACTS) {
  const full = join(ARTIFACTS, artifactPath);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(full, "utf8"));
  } catch {
    console.error(`[abis] missing artifact ${artifactPath} — run 'hardhat compile' first`);
    process.exit(1);
  }

  const file = exportName.replace(/Abi$/, "");
  const body = JSON.stringify(artifact.abi, null, 2);

  writeFileSync(
    join(OUT_DIR, `${file}.ts`),
    `// AUTO-GENERATED by packages/contracts/scripts/generate-abis.mjs\n` +
      `// Do not edit by hand — run \`npm run compile\` to regenerate.\n` +
      `export const ${exportName} = ${body} as const;\n`,
  );

  const events = artifact.abi.filter((e) => e.type === "event").length;
  const fns = artifact.abi.filter((e) => e.type === "function").length;
  console.log(`[abis] ${file}.ts — ${fns} functions, ${events} events`);
}
