// AUTO-GENERATED by packages/contracts/scripts/deploy.ts — do not edit by hand.
// Zero addresses until the first deploy runs.
export const addresses = {
  MockUSDC: "0x0000000000000000000000000000000000000000",
  JobContract: "0x0000000000000000000000000000000000000000",
  IdentityRegistry: "0x0000000000000000000000000000000000000000",
  ReputationRegistry: "0x0000000000000000000000000000000000000000",
  EvaluatorModule: "0x0000000000000000000000000000000000000000",
} as const;

export type ContractName = keyof typeof addresses;
