// AUTO-GENERATED by packages/contracts/scripts/deploy.ts — do not edit by hand.
// Keyed by chain id. Deploying to one chain preserves the other chains' entries.
// Zero addresses mean "not deployed to that chain yet".
import type { ContractAddresses } from "./types";

export const deployments: Record<number, ContractAddresses> = {
  "31337": {
    MockUSDC: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    JobContract: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    IdentityRegistry: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
    ReputationRegistry: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    EvaluatorModule: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
  },
  "84532": {
    MockUSDC: "0xf705b1b3c721e85c7f84a9bfab2fecb0e15d3c49",
    JobContract: "0x6f2c4373893a35c8cedd4c0af1ad974b7e4ecd21",
    IdentityRegistry: "0x1e6678cb0578ac4b24a3735ee85457f13a6cec96",
    ReputationRegistry: "0x9e8fa035988f134ebbf712398dbe00a5efa99667",
    EvaluatorModule: "0xd15b47e52e956861b2d5836f942846ce0702d588",
  },
};

export const deploymentBlocks: Record<number, number> = {
  "31337": 0,
  "84532": 44820110,
};
