// AUTO-GENERATED by packages/contracts/scripts/deploy.ts — do not edit by hand.
// Keyed by chain id. Deploying to one chain preserves the other chains' entries.
// Zero addresses mean "not deployed to that chain yet".
import type { ContractAddresses } from "./types";

export const deployments: Record<number, ContractAddresses> = {
  "31337": {
    MockUSDC: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    JobContract: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    IdentityRegistry: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
    ReputationRegistry: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    EvaluatorModule: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
  },
  "84532": {
    MockUSDC: "0x75e9e2eefc3eca12ac4d6107b28b8b930486d021",
    JobContract: "0x25c7852c13b3e624fb26589360c4634651dd83cb",
    IdentityRegistry: "0x3290f750e3670798daad34656bc733fb64334220",
    ReputationRegistry: "0x88126a66e0d72514957c485bd91843b1252f0ab6",
    EvaluatorModule: "0x7089233e15ecad5f840d0ca1b458a4965a214963",
  },
};

export const deploymentBlocks: Record<number, number> = {
  "31337": 0,
  "84532": 44819047,
};
