// AUTO-GENERATED by packages/contracts/scripts/deploy.ts — do not edit by hand.
// Keyed by chain id. Deploying to one chain preserves the other chains' entries.
// Zero addresses mean "not deployed to that chain yet".
import type { ContractAddresses } from "./types";

export const deployments: Record<number, ContractAddresses> = {
  "31337": {
    MockUSDC: "0x0000000000000000000000000000000000000000",
    JobContract: "0x0000000000000000000000000000000000000000",
    IdentityRegistry: "0x0000000000000000000000000000000000000000",
    ReputationRegistry: "0x0000000000000000000000000000000000000000",
    EvaluatorModule: "0x0000000000000000000000000000000000000000",
  },
};

export const deploymentBlocks: Record<number, number> = {
  "31337": 0,
};
